from __future__ import annotations

import json
from typing import Any

from fastapi.encoders import jsonable_encoder

from app.orchestrator.llm import (
    BaseLLMProvider,
    LLMMessage,
    LLMProviderError,
    LLMRequest,
    OpenRouterProvider,
)
from app.orchestrator.modules.base_module import BaseModule
from app.orchestrator.schemas.module_response import ModuleResponse
from app.orchestrator.schemas.student_context import StudentContext
from app.student.domains.scheduling.engine import (
    CandidateGenerator,
    CandidateValidationService,
    PreferenceScoringService,
    ScheduleMetricsService,
    ScheduleRankingService,
)
from app.student.domains.scheduling.schemas.decision import (
    DecisionStatus,
    ScheduleDecisionRequest,
    ScheduleDecisionResult,
)
from app.student.domains.scheduling.schemas.session import StartSessionRequest
from app.student.domains.scheduling.services.decision_service import ScheduleDecisionService
from app.student.domains.scheduling.services.retrieval_service import (
    SchedulePilotRetrievalService,
    schedulepilot_retrieval_service,
)
from app.student.domains.scheduling.services.session_service import (
    SchedulingSessionService,
    scheduling_session_service,
)

MODULE_NAME = "scheduling"
MODULE_DESCRIPTION = "Build and explain student course schedules."
MODULE_VERSION = "1.0.0"
IMPLEMENTATION_PHASE = "Phase D2"

SCHEDULEPILOT_ADVISOR_PROMPT = (
    "You are EdPlan's SchedulePilot advisor. Explain deterministic schedule "
    "candidates generated by EdPlan's scheduling engine. Never invent courses, "
    "sections, meeting times, instructors, rooms, conflicts, or rankings. Recommend "
    "from the provided candidate schedules only. Keep the response concise and "
    "action-oriented."
)


class SchedulePilotModule(BaseModule):
    """Orchestrator module adapter for deterministic SchedulePilot workflows."""

    name = MODULE_NAME
    description = MODULE_DESCRIPTION

    def __init__(
        self,
        db=None,
        retrieval_service: SchedulePilotRetrievalService | None = None,
        candidate_generator: CandidateGenerator | None = None,
        validation_service: CandidateValidationService | None = None,
        metrics_service: ScheduleMetricsService | None = None,
        scoring_service: PreferenceScoringService | None = None,
        ranking_service: ScheduleRankingService | None = None,
        decision_service: ScheduleDecisionService | None = None,
        session_service: SchedulingSessionService | None = None,
        llm_provider: BaseLLMProvider | None = None,
    ) -> None:
        self.db = db
        self.retrieval_service = retrieval_service or schedulepilot_retrieval_service
        self.candidate_generator = candidate_generator or CandidateGenerator()
        self.validation_service = validation_service or CandidateValidationService()
        self.metrics_service = metrics_service or ScheduleMetricsService()
        self.scoring_service = scoring_service or PreferenceScoringService()
        self.ranking_service = ranking_service or ScheduleRankingService()
        self.decision_service = decision_service or ScheduleDecisionService(
            retrieval_service=self.retrieval_service,
            candidate_generator=self.candidate_generator,
            validation_service=self.validation_service,
            metrics_service=self.metrics_service,
            scoring_service=self.scoring_service,
            ranking_service=self.ranking_service,
        )
        self.session_service = session_service or scheduling_session_service
        self.llm_provider = llm_provider or OpenRouterProvider()

    async def execute(self, context: StudentContext, query: str) -> ModuleResponse:
        """Retrieve scheduling context and generate deterministic candidates."""
        if self.db is None:
            return self._clarification_response(["database_session"])

        user = context.user or {}
        plan = context.plan or {}
        user_id = user.get("id")
        plan_id = plan.get("plan_id")
        if not isinstance(user_id, int):
            return self._clarification_response(["student_profile"])
        if not plan_id:
            return self._clarification_response(["active_academic_plan"])

        term_id = plan.get("term_id") or plan.get("selected_term_id")
        session = self.session_service.create_session(
            StartSessionRequest(
                user_id=user_id,
                plan_id=str(plan_id),
                term_id=term_id,
                query=query,
                preferences=context.preferences,
            )
        )
        decision = await self.decision_service.decide_and_generate(
            self.db,
            ScheduleDecisionRequest(
                user_id=user_id,
                plan_id=str(plan_id),
                term_id=term_id,
                query=query,
                preferences=context.preferences,
            ),
        )
        session = self.session_service.apply_decision(session.state.session_id, decision)
        return await _decision_response(self, decision, query, context, session=session)

    def _clarification_response(self, missing: list[str]) -> ModuleResponse:
        readable = ", ".join(item.replace("_", " ") for item in missing)
        return ModuleResponse(
            module_name=self.name,
            content=(
                "I can build optimized schedules after you have an active academic plan. "
                f"I still need: {readable}. Please generate or select your PathCrafter "
                "academic plan first."
            ),
            data={"missing_context": missing},
            confidence=0.35,
            metadata={
                "description": self.description,
                "module_version": MODULE_VERSION,
                "implementation_phase": IMPLEMENTATION_PHASE,
                "status": DecisionStatus.NEEDS_INPUT,
                "next_action": "ask_for_plan",
                "reason": "missing_schedule_context",
                "warnings": [],
                "errors": [],
            },
        )


async def _decision_response(
    module: SchedulePilotModule,
    decision: ScheduleDecisionResult,
    query: str,
    context: StudentContext,
    *,
    session=None,
) -> ModuleResponse:
    schedule_plan = _structured_schedule_plan(decision, context, query)
    advisor_content, llm_status = await _advisor_response(module, decision, schedule_plan, query)
    data = {
        "decision": decision.model_dump(
            mode="json",
            exclude={
                "retrieval_context",
                "ranking_result",
                "scored_candidates",
            },
        ),
        "schedule_plan": schedule_plan,
        "schedule_summary": schedule_plan["summary"],
    }
    if session is not None:
        data["session"] = session.model_dump(mode="json")
    counts = _counts(decision)

    if decision.retrieval_context is not None:
        data.update(decision.retrieval_context.model_dump(mode="json"))
    if decision.ranking_result is not None:
        data["candidates"] = list(decision.scored_candidates)
        data["validated_candidates"] = data["candidates"]
        data["scored_candidates"] = data["candidates"]
        data["ranked_options"] = [
            option.model_dump(mode="json") for option in decision.ranking_result.options
        ]
        data["top_option"] = (
            decision.ranking_result.top_option.model_dump(mode="json")
            if decision.ranking_result.top_option is not None
            else None
        )
        data["ranking_metadata"] = decision.ranking_result.metadata.model_dump(mode="json")
    else:
        data["candidates"] = []
        data["validated_candidates"] = []
        data["scored_candidates"] = []
        data["ranked_options"] = []
        data["top_option"] = None
        data["ranking_metadata"] = {}
    if decision.generation_metadata is not None:
        data["generation_metadata"] = decision.generation_metadata
    if decision.validation_metadata is not None:
        data["validation_metadata"] = decision.validation_metadata
    if decision.metrics_metadata is not None:
        data["metrics_metadata"] = decision.metrics_metadata
    if decision.scoring_metadata is not None:
        data["scoring_metadata"] = decision.scoring_metadata
    data["generation_warnings"] = list(decision.generation_warnings)

    content = advisor_content or _content_for_decision(decision, schedule_plan)
    confidence = 0.78 if decision.status in {DecisionStatus.OK, DecisionStatus.WARNING} else 0.4
    return ModuleResponse(
        module_name=module.name,
        content=content,
        data=data,
        confidence=confidence,
        metadata={
            "description": module.description,
            "module_version": MODULE_VERSION,
            "implementation_phase": IMPLEMENTATION_PHASE,
            "status": decision.status,
            "next_action": decision.next_action,
            "reason": decision.reason,
            "warnings": schedule_plan["warnings"],
            "errors": list(decision.errors),
            "query": query,
            "advisor_prompt": "scheduling.advisor",
            "llm_status": llm_status,
            "counts": counts,
            "candidate_generation_implemented": True,
            "conflict_detection_implemented": True,
            "feasibility_validation_implemented": True,
            "metrics_implemented": True,
            "scoring_implemented": True,
            "ranking_implemented": True,
            "decision_engine_implemented": True,
            "interaction_session_implemented": True,
            "persistence_implemented": False,
        },
    )


async def _advisor_response(
    module: SchedulePilotModule,
    decision: ScheduleDecisionResult,
    schedule_plan: dict[str, Any],
    query: str,
) -> tuple[str | None, str]:
    if decision.status not in {DecisionStatus.OK, DecisionStatus.WARNING, DecisionStatus.PARTIAL}:
        return None, "skipped"
    payload = {
        "student": schedule_plan["student"],
        "academic_plan": schedule_plan["academic_plan"],
        "candidate_schedules": schedule_plan["candidate_schedules"][:3],
        "validation": schedule_plan["validation"],
        "warnings": schedule_plan["warnings"],
        "student_preferences": schedule_plan["student_preferences"],
        "student_query": query,
    }
    try:
        response = await module.llm_provider.generate(
            LLMRequest(
                messages=[
                    LLMMessage(
                        role="user",
                        content=(
                            "Explain the recommended schedule using only this structured "
                            "SchedulePilot output. Do not create or modify schedules.\n\n"
                            f"{json.dumps(jsonable_encoder(payload))}"
                        ),
                    )
                ],
                system_prompt=SCHEDULEPILOT_ADVISOR_PROMPT,
                tools=[],
                temperature=0.2,
                max_tokens=1200,
                metadata={"module": MODULE_NAME, "mode": "schedule_explanation"},
            )
        )
    except LLMProviderError:
        return None, "unavailable"
    except Exception:
        return None, "failed"
    if not response.content:
        return None, "empty"
    return response.content, "ok"


def _structured_schedule_plan(
    decision: ScheduleDecisionResult,
    context: StudentContext,
    query: str,
) -> dict[str, Any]:
    retrieval_context = decision.retrieval_context
    options = decision.ranking_result.options if decision.ranking_result is not None else []
    candidate_schedules = [_schedule_option_payload(option) for option in options]
    recommended_schedule = candidate_schedules[0] if candidate_schedules else None
    validation = _validation_payload(decision, candidate_schedules)
    warnings = _schedule_warnings(decision, validation)
    term_id = decision.context.resolved_term_id
    term_name = None
    if retrieval_context is not None:
        term_name = next(
            (term.term_name for term in retrieval_context.terms if term.term_id == term_id),
            None,
        )
    summary = {
        "status": decision.status,
        "reason": decision.reason,
        "next_action": decision.next_action,
        "term_id": term_id,
        "term_name": term_name,
        "candidate_count": len(candidate_schedules),
        "recommended_option_id": (
            recommended_schedule.get("option_id") if recommended_schedule else None
        ),
        "recommended_score": (
            recommended_schedule.get("normalized_score") if recommended_schedule else None
        ),
        "recommended_credits": (
            recommended_schedule.get("metrics", {}).get("total_credits")
            if recommended_schedule
            else 0
        ),
        "recommended_campus_days": (
            recommended_schedule.get("metrics", {}).get("campus_days")
            if recommended_schedule
            else 0
        ),
    }
    return {
        "summary": summary,
        "student": {"user": context.user, "preferences": context.preferences},
        "academic_plan": {
            "plan": (
                retrieval_context.plan.model_dump(mode="json")
                if retrieval_context is not None
                else context.plan
            ),
            "courses": (
                [course.model_dump(mode="json") for course in retrieval_context.courses]
                if retrieval_context is not None
                else []
            ),
        },
        "recommended_schedule": recommended_schedule,
        "alternative_schedules": candidate_schedules[1:],
        "candidate_schedules": candidate_schedules,
        "weekly_timetable": (
            recommended_schedule.get("weekly_timetable") if recommended_schedule else []
        ),
        "validation": validation,
        "warnings": warnings,
        "advisor_notes": [],
        "recommendations": _recommendations(decision, recommended_schedule, warnings),
        "student_preferences": context.preferences,
        "original_request": query,
    }


def _schedule_option_payload(option) -> dict[str, Any]:
    sections = [section.model_dump(mode="json") for section in option.selected_sections]
    meetings = [meeting.model_dump(mode="json") for meeting in option.selected_meetings]
    metrics = option.metrics.model_dump(mode="json") if option.metrics is not None else {}
    conflicts = [conflict.model_dump(mode="json") for conflict in option.conflicts]
    warnings = [warning.model_dump(mode="json") for warning in option.warnings]
    return {
        "option_id": option.option_id,
        "rank": option.rank,
        "score": option.score,
        "normalized_score": option.normalized_score,
        "sections": sections,
        "meetings": meetings,
        "weekly_timetable": _weekly_timetable(sections, meetings),
        "metrics": metrics,
        "validation": {
            "is_valid": len(conflicts) == 0,
            "conflicts": conflicts,
            "warnings": warnings,
        },
        "explanation": option.explanation,
        "tradeoffs": list(option.tradeoffs),
        "metadata": option.metadata,
    }


def _weekly_timetable(
    sections: list[dict[str, Any]],
    meetings: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    sections_by_id = {section["section_id"]: section for section in sections}
    rows = []
    for meeting in sorted(
        meetings,
        key=lambda item: (
            item.get("weekday") or 99,
            item.get("start_time") or "",
            item.get("section_id") or "",
        ),
    ):
        section = sections_by_id.get(meeting.get("section_id"), {})
        rows.append(
            {
                "weekday": meeting.get("weekday"),
                "day": _weekday_name(meeting.get("weekday")),
                "start_time": meeting.get("start_time"),
                "end_time": meeting.get("end_time"),
                "course_id": section.get("course_id"),
                "section_id": section.get("section_id"),
                "section_number": section.get("section_number"),
                "instructor": section.get("instructor"),
                "room": meeting.get("room"),
                "building": meeting.get("building"),
                "meeting_type": meeting.get("meeting_type"),
                "is_async": meeting.get("is_async"),
            }
        )
    return rows


def _validation_payload(
    decision: ScheduleDecisionResult,
    candidate_schedules: list[dict[str, Any]],
) -> dict[str, Any]:
    conflict_count = sum(
        len(schedule["validation"]["conflicts"]) for schedule in candidate_schedules
    )
    warning_count = sum(
        len(schedule["validation"]["warnings"]) for schedule in candidate_schedules
    )
    recommended = candidate_schedules[0] if candidate_schedules else None
    return {
        "status": "warning" if decision.warnings or warning_count else "valid",
        "empty_schedule": len(candidate_schedules) == 0,
        "candidate_count": len(candidate_schedules),
        "conflict_count": conflict_count,
        "warning_count": warning_count,
        "recommended_is_valid": (
            recommended["validation"]["is_valid"] if recommended is not None else False
        ),
        "details": decision.validation_metadata or {},
    }


def _schedule_warnings(
    decision: ScheduleDecisionResult,
    validation: dict[str, Any],
) -> list[str]:
    warnings = list(decision.warnings) + list(decision.generation_warnings)
    if validation["empty_schedule"]:
        warnings.append("No complete feasible schedule could be generated.")
    if validation["conflict_count"]:
        warnings.append("One or more generated schedules contain validation conflicts.")
    return _unique_strings(warnings)


def _recommendations(
    decision: ScheduleDecisionResult,
    recommended_schedule: dict[str, Any] | None,
    warnings: list[str],
) -> list[str]:
    recommendations = []
    if recommended_schedule is not None:
        recommendations.append("Review the recommended schedule before registration.")
        if recommended_schedule.get("metrics", {}).get("total_gap_minutes", 0) > 0:
            recommendations.append("Check whether the gaps between classes fit your day.")
    if warnings:
        recommendations.append("Resolve schedule warnings before finalizing registration.")
    if decision.status == DecisionStatus.NEEDS_INPUT:
        recommendations.append("Select an active academic plan and term before scheduling.")
    return recommendations


def _content_for_decision(
    decision: ScheduleDecisionResult,
    schedule_plan: dict[str, Any] | None = None,
) -> str:
    if decision.status == DecisionStatus.OK:
        if schedule_plan and schedule_plan.get("recommended_schedule"):
            summary = schedule_plan["summary"]
            return (
                f"Generated schedules for {summary.get('term_name') or 'the selected term'}. "
                f"SchedulePilot found {summary['candidate_count']} schedule option"
                f"{'' if summary['candidate_count'] == 1 else 's'} for "
                f"review. The recommended schedule has {summary['recommended_credits']} credits and "
                f"{summary['recommended_campus_days']} campus day"
                f"{'' if summary['recommended_campus_days'] == 1 else 's'}."
            )
        return decision.explanation or "Schedule options generated successfully."
    if decision.status == DecisionStatus.WARNING:
        return decision.explanation or "Schedule options generated with warnings."
    if decision.status == DecisionStatus.NEEDS_INPUT:
        if decision.reason == "no_plans":
            return (
                "I can optimize your semester schedule after you create an academic "
                "plan with PathCrafter."
            )
        return "More information is needed before schedule generation can begin."
    if decision.status == DecisionStatus.PARTIAL:
        return "SchedulePilot produced a partial scheduling result."
    return "SchedulePilot could not generate schedules for the current request."


def _counts(decision: ScheduleDecisionResult) -> dict[str, int]:
    counts = {
        "courses": 0,
        "terms": 0,
        "offerings": 0,
        "sections": 0,
        "meetings": 0,
        "candidates": 0,
        "scored_candidates": 0,
        "ranked_options": 0,
        "feasible_candidates": 0,
        "infeasible_candidates": 0,
    }
    if decision.retrieval_context is not None:
        counts.update(
            {
                "courses": len(decision.retrieval_context.courses),
                "terms": len(decision.retrieval_context.terms),
                "offerings": len(decision.retrieval_context.offerings),
                "sections": len(decision.retrieval_context.sections),
                "meetings": len(decision.retrieval_context.meetings),
            }
        )
    if decision.ranking_result is not None:
        counts["candidates"] = len(decision.scored_candidates)
        counts["scored_candidates"] = len(decision.scored_candidates)
        counts["ranked_options"] = len(decision.ranking_result.options)
        counts["feasible_candidates"] = decision.ranking_result.metadata.feasible_candidates
    if decision.validation_metadata is not None:
        counts["feasible_candidates"] = decision.validation_metadata.get("feasible_count", 0)
        counts["infeasible_candidates"] = decision.validation_metadata.get("infeasible_count", 0)
    return counts


def _weekday_name(value: Any) -> str | None:
    names = {
        1: "Monday",
        2: "Tuesday",
        3: "Wednesday",
        4: "Thursday",
        5: "Friday",
        6: "Saturday",
        7: "Sunday",
    }
    return names.get(value)


def _unique_strings(values: list[str]) -> list[str]:
    unique_values = []
    for value in values:
        if value and value not in unique_values:
            unique_values.append(value)
    return unique_values
